# Generated by Django 4.0 on 2021-12-23 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_heardofcodum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('individual_artist', 'Individual Artist'), ('theatre_group', 'Theatre Group')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='perform',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='some_details_page',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
