# Generated by Django 4.0 on 2021-12-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='what_you_like_doing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
