# Generated by Django 4.0 on 2022-01-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_what_you_like_doing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='basics_18_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='privacy_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile-images/'),
        ),
    ]
