# Generated by Django 4.0 on 2022-01-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_basics_18_plus_profile_privacy_agreement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='some_details_page',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='what_you_like_doing',
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('individual_artist', 'Individual Artist'), ('theatre_group', 'Theatre Group')], default='individual_artist', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='perform',
            field=models.CharField(choices=[('on_stage', 'On Stage'), ('off_stage', 'Off Stage'), ('both', 'Both')], default='on_stage', max_length=255),
        ),
    ]
