# Generated by Django 4.0 on 2022-01-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_some_details_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsianIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('east_asian', models.BooleanField(default=False)),
                ('south_east_asian', models.BooleanField(default=False)),
                ('south_asian', models.BooleanField(default=False)),
                ('central_west_asian', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GetSomeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('pronouns', models.CharField(choices=[('x1', 'X1'), ('x2', 'X2')], default='x1', max_length=255)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('lgbtqia_community_identification', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('do_not_wish', 'Do_Not_Wish')], default='yes', max_length=255)),
                ('black_or_african_american', models.BooleanField(default=False)),
                ('indigenous', models.BooleanField(default=False)),
                ('latinx', models.BooleanField(default=False)),
                ('mena', models.BooleanField(default=False)),
                ('native_hawailan_or_other_pacific_islander', models.BooleanField(default=False)),
                ('white', models.BooleanField(default=False)),
                ('feet', models.IntegerField(default=0)),
                ('inches', models.FloatField(default=0.0)),
                ('i_do_not_wish_to_answer', models.BooleanField(default=False)),
                ('age_range', models.CharField(choices=[('18-22', 'Eighteen to Twenty Two'), ('23-27', 'Twenty Three to Twenty Seven'), ('28-32', 'Twenty Eight to Thirty Two'), ('33-37', 'Thirty Three to Thirty Seven'), ('38-42', 'Thirty Eight to Fourty Two'), ('43-47', 'Fourty Three to Fourty Seven'), ('48-52', 'Fourty Eight to Fifty Two'), ('53-57', 'Fifty Three to Fifty Seven'), ('58-62', 'Fifty Eight to Sixty Two'), ('62+', 'Sixty Two Plus')], default='18-22', max_length=255)),
                ('gender_identity', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=255)),
                ('women', models.BooleanField(default=False)),
                ('men', models.BooleanField(default=False)),
                ('neither', models.BooleanField(default=False)),
                ('playing_character_throgh_transition', models.BooleanField(default=False)),
                ('asian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.asianidentity')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_get_some_details', to='accounts.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
