# Generated by Django 4.0 on 2022-01-28 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_asianidentity_getsomedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getsomedetails',
            name='asian',
        ),
        migrations.AddField(
            model_name='asianidentity',
            name='get_some_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.getsomedetails'),
        ),
    ]
