# Generated by Django 4.0 on 2022-01-28 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_getsomedetails_asian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatDoYouLikeDoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('directing', models.BooleanField(default=False)),
                ('violence_fight_design', models.BooleanField(default=False)),
                ('intimacy_design', models.BooleanField(default=False)),
                ('choreography', models.BooleanField(default=False)),
                ('casting', models.BooleanField(default=False)),
                ('dramaturgy', models.BooleanField(default=False)),
                ('dialect_coaching', models.BooleanField(default=False)),
                ('musical_directing', models.BooleanField(default=False)),
                ('stage_management', models.BooleanField(default=False)),
                ('production_management', models.BooleanField(default=False)),
                ('board_op', models.BooleanField(default=False)),
                ('run_crew', models.BooleanField(default=False)),
                ('set_design', models.BooleanField(default=False)),
                ('technical_direction', models.BooleanField(default=False)),
                ('properties_designer', models.BooleanField(default=False)),
                ('scenic_carpentery', models.BooleanField(default=False)),
                ('charge_artist', models.BooleanField(default=False)),
                ('light_design', models.BooleanField(default=False)),
                ('projection_design', models.BooleanField(default=False)),
                ('special_effect_design', models.BooleanField(default=False)),
                ('master_electrician', models.BooleanField(default=False)),
                ('sound_design', models.BooleanField(default=False)),
                ('sound_mixer_engineer', models.BooleanField(default=False)),
                ('costume_design', models.BooleanField(default=False)),
                ('hair_and_wig_design', models.BooleanField(default=False)),
                ('makeup_design', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_what_you_like_doing', to='accounts.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
