# Generated by Django 4.0 on 2022-01-28 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_whatdoyoulikedoing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmostDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('union', models.CharField(choices=[('x1', 'X1'), ('x2', 'X2')], default='x1', max_length=255)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_almost_done', to='accounts.customuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
