# Generated by Django 4.0 on 2022-01-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_almostdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almostdone',
            name='union',
            field=models.CharField(choices=[('agency', 'Agency')], default='agency', max_length=255),
        ),
    ]
