# Generated by Django 4.0 on 2022-02-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_created_date_almostdone_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'In Active')], default='active', max_length=255),
        ),
    ]
