# Generated by Django 4.0 on 2022-02-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asianidentity',
            name='get_some_details',
        ),
        migrations.RemoveField(
            model_name='getsomedetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='whatdoyoulikedoing',
            name='user',
        ),
        migrations.DeleteModel(
            name='AlmostDone',
        ),
        migrations.DeleteModel(
            name='AsianIdentity',
        ),
        migrations.DeleteModel(
            name='GetSomeDetails',
        ),
        migrations.DeleteModel(
            name='WhatDoYouLikeDoing',
        ),
    ]
