# Generated by Django 4.0 on 2022-02-09 13:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_asianidentity_get_some_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='basics_18_plus',
            new_name='height_no_answer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='perform',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='privacy_agreement',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='age_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_transition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='height_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_inches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lgbtqia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='offstage_general',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='offstage_hair_makeup_costumes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='offstage_lighting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='offstage_production',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='offstage_scenic_and_properties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='offstage_sound',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default='', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='union_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='websites',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
