# Generated by Django 4.0 on 2022-02-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_basicprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicProfile',
        ),
    ]
