# Generated by Django 4.0 on 2022-02-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_basicprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicProfile',
        ),
    ]
