# Generated by Django 4.0 on 2022-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_basicprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicprofile',
            name='websites',
            field=models.JSONField(default=list),
        ),
    ]
